version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autobase2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    